# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_NAME: warehouse
  RUN_REGION: europe-west4
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  DBHOST: ${{ secrets.GCPDBHOST }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $PROJECT_NAME --image gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA --platform managed --region $RUN_REGION --add-cloudsql-instances=${DBHOST}

